# French translations for vdi.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the vdi project.
#
# Translators:
# c <cverheyd@hotmail.com>, 2014
# Loïc Chabert <chabert.loic.74@gmail.com>, 2013
# François Bureau <francois.bureau@cloudwatt.com>, 2013
msgid ""
msgstr ""
"Project-Id-Version:  VDI\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-03-20 06:06+0000\n"
"PO-Revision-Date: 2014-03-19 22:46+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French "
"(http://www.transifex.com/projects/p/openstack/language/fr/)\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: vdi/openstack/common/exception.py:103
msgid "Uncaught exception"
msgstr "Exception non interceptée"

#: vdi/openstack/common/fileutils.py:63
#, python-format
msgid "Reloading cached file %s"
msgstr "Rechargement du fichier mis en mémoire cache %s"

#: vdi/openstack/common/gettextutils.py:297
msgid "Message objects do not support addition."
msgstr "Les objets message ne supportent pas l'addition."

#: vdi/openstack/common/gettextutils.py:306
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"Les objets message ne supportent pas str() parce qu'il peuvent contenir "
"des caractères non-ascii. Utiliser unicode() ou translate() à la place."

#: vdi/openstack/common/lockutils.py:103
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Impossible de relâcher le verrou acquis `%s`"

#: vdi/openstack/common/lockutils.py:168
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr "Sémaphore \"%(lock)s\" obtenu"

#: vdi/openstack/common/lockutils.py:177
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr "Tentative d'appropriation du fichier verrouillé \"%(lock)s\""

#: vdi/openstack/common/lockutils.py:187
#, python-format
msgid "Created lock path: %s"
msgstr "Chemin de verrou créé: %s"

#: vdi/openstack/common/lockutils.py:205
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr "Verrou de fichier \"%(lock)s\" obtenu au niveau de %(path)s"

#: vdi/openstack/common/lockutils.py:209
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr "Verrou de fichier \"%(lock)s\" libéré au niveau de %(path)s"

#: vdi/openstack/common/lockutils.py:247
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr "Sémaphore / verrou \"%(function)s\" obtenu"

#: vdi/openstack/common/lockutils.py:251
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr "Sémaphore / verrou \"%(function)s\" libéré"

#: vdi/openstack/common/log.py:326
#, python-format
msgid "Deprecated: %s"
msgstr "Obsolète: %s"

#: vdi/openstack/common/log.py:437
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""
"Erreur lors du chargement de la configuration de connexion "
"%(log_config)s: %(err_msg)s"

#: vdi/openstack/common/log.py:488
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "la fonction syslog doit correspondre à l'une des options suivantes : %s"

#: vdi/openstack/common/log.py:709
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Appel fatal adressé à une configuration obsolète : %(msg)s"

#: vdi/openstack/common/periodic_task.py:39
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr "Argument inattendu pour la création de tâche périodique : %(arg)s."

#: vdi/openstack/common/processutils.py:58
msgid "Unexpected error while running command."
msgstr "Erreur inattendue lors de l’exécution de la commande."

#: vdi/openstack/common/processutils.py:61
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Commande: %(cmd)s\n"
"Code de sortie: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: vdi/openstack/common/processutils.py:139
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "Arguments de mot clé inconnus obtenus pour utils.execute : %r"

#: vdi/openstack/common/processutils.py:145
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: vdi/openstack/common/processutils.py:241
msgid "Environment not supported over SSH"
msgstr "Environnement non pris en charge sur SSH"

#: vdi/openstack/common/processutils.py:245
msgid "process_input not supported over SSH"
msgstr "process_input non pris en charge sur SSH"

#: vdi/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr "Impossible de trouver cert_file : %s"

#: vdi/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr "Impossible de trouver ca_file : %s"

#: vdi/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr "Impossible de trouver key_file : %s"

#: vdi/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"Lors de l'exécution du serveur en mode SSL, vous devez spécifier une "
"valeur d'option cert_file et key_file dans votre fichier de configuration"

#: vdi/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr "Version de SSL invalide : %s"

#: vdi/openstack/common/wsgi.py:187
msgid "cannot understand JSON"
msgstr "impossible de comprendre JSON"

#: vdi/openstack/common/wsgi.py:211
msgid "cannot understand XML"
msgstr "impossible de comprendre XML"

#: vdi/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr "Une erreur inconnue s'est produite avec les outils crypto."

#: vdi/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr "La taille du block %(given)d est trop grande. max = %(maximum)d"

#: vdi/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr "%(given)d est trop longue. max = %(maximum)d"

#: vdi/openstack/common/db/exception.py:42
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr "Paramètre invalide: La base de donnée ne supporte pas Unicode."

#: vdi/openstack/common/db/sqlalchemy/migration.py:191
msgid "version should be an integer"
msgstr "version doit être un entier"

#: vdi/openstack/common/db/sqlalchemy/migration.py:214
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""
"Les tables \"%s\" ont une collation non utf8, assurez-vous que pour "
"toutes les tables CHARSET=utf8."

#: vdi/openstack/common/db/sqlalchemy/migration.py:238
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""
"La base de données n'est pas versionnée, mais contient des tables. "
"Veuillez indiquer manuellement la version courante du schéma."

#: vdi/openstack/common/db/sqlalchemy/session.py:596
msgid "DB exception wrapped."
msgstr "Exception BD encapsulée."

#: vdi/openstack/common/db/sqlalchemy/session.py:665
#, python-format
msgid "Database server has gone away: %s"
msgstr "Le serveur de base de données a disparu: %s"

#: vdi/openstack/common/db/sqlalchemy/session.py:743
msgid ""
"This application has not enabled MySQL traditional mode, which means "
"silent data corruption may occur. Please encourage the application "
"developers to enable this mode."
msgstr ""

#: vdi/openstack/common/db/sqlalchemy/session.py:767
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr "Echec de connexion SQL. %s essais restants."

#: vdi/openstack/common/db/sqlalchemy/test_migrations.py:63
#, python-format
msgid "Got lock \"%s\""
msgstr "Verrou \"%s\" obtenu"

#: vdi/openstack/common/db/sqlalchemy/test_migrations.py:66
#, python-format
msgid "Lock released \"%s\""
msgstr "Verrou \"%s\" relaché"

#: vdi/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr "Clé de tri fournie invalide."

#: vdi/openstack/common/db/sqlalchemy/utils.py:97
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "ID absent de sort_keys ; sort_keys unique ?"

#: vdi/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Sens de tri inconnu, doit être 'desc' ou 'asc'"

#: vdi/openstack/common/db/sqlalchemy/utils.py:194
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""
"Spécifiez la colonne %s dans le paramètre col_name_col_instance. Ceci est"
" obligatoire car la colonne a un type non pris en charge dans sqlite)."

#: vdi/openstack/common/db/sqlalchemy/utils.py:200
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""
"Le paramètre col_name_col_instance contient un type d'instance de colonne"
" incorrect pour la colonne %s. Il devrait être une instance de "
"sqlalchemy.Column."

#: vdi/openstack/common/db/sqlalchemy/utils.py:280
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr "Suppression ligne en double avec l'ID : %(id)s de la table : %(table)s"

#: vdi/openstack/common/db/sqlalchemy/utils.py:301
msgid "Unsupported id columns type"
msgstr "Type de colonnes id non pris en charge"

